### ISSUE TITLE
Что значит YesAllWomen?

### ISSUE THREAD

**Issue by alexgrinseit** [alinakulmagambetova/readup#1]
https://github.com/alinakulmagambetova/readup/blob/36701a9b5eeeaf2f53add557000f48c36b17cbcc/index.html#L76

**Comment by alinakulmagambetova** [comment]
это хэштег, по которому можно почитат истории в твиттере.

**Comment by alexgrinseit** [comment]
Это понятно, а что значит само AllWomen, это мем?

**Comment by alinakulmagambetova** [comment]
не совсем. на западных форумах есть распространенное "не все мужики такие!", и это своего рода ответное "у всех женщин такие проблемы, интересно, почему?"
